# Generated by Django 4.2.2 on 2023-06-08 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_rename_crud_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='decription',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='itemname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='slno',
            new_name='num',
        ),
    ]
